id: P000303
initial_creation_type: ocr
created_at: 10/03/2020
last_modified_at: 2021-12-16 15:32:57.272276
source_metadata:
  id: bdr:W1KG12025
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་སྤྱི་དོན་དང་གཞུང་འགྲེལ།
  author: ''
  volumes:
    90cb71b9840244b89ef6c98fec58575c:
      image_group_id: I1KG12058
      title: Volume 1 of spyod 'jug shes rab le'u'i spyi don dang gzhung 'grel/
      volume_number: 1
      total_pages: 450
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
