id: opecha:P000303
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG12025
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་སྤྱི་དོན་དང་གཞུང་འགྲེལ།
  volume:
    90cb71b9840244b89ef6c98fec58575c:
      image_group_id: I1KG12058
      title: Volume 1 of spyod 'jug shes rab le'u'i spyi don dang gzhung 'grel/
      volume_number: 1
      total_pages: 450
  author: ''
ebook_metadata:
  title: སྤྱོད་འཇུག་ཤེས་རབ་ལེའུའི་སྤྱི་དོན་དང་གཞུང་འགྲེལ།
  author: ''
  sku: P000303
  cover: cover.jpg
  layers:
  - pagination
